### ISSUE TITLE
Can't find on market (page not exist?)

### ISSUE THREAD

**Issue by LonkingPark** [neozhu/CleanArchitectureCodeGenerator#1]
![image](https://user-images.githubusercontent.com/85411409/130511330-da4d8bf6-b947-4fc6-86c5-b6bf9c9e25d3.png)
![image](https://user-images.githubusercontent.com/85411409/130511514-92c1ee85-976b-4e8c-b3a0-585d8873ab1e.png)

**Comment by neozhu** [comment]
please, clone this project and compile it, and install  src\bin\Debug\CleanArchitectureCodeGenerator.vsix 
or download from  https://marketplace.visualstudio.com/items?itemName=SmartCodeMVC5Enginever3898.247365

**Comment by LonkingPark** [comment]
I did that, just informing that it was not public :)
