### ISSUE TITLE
Visual Studio Version 16.11.3 - Showing COM object error on clicking the "Add Feature" button

### ISSUE THREAD

**Issue by Gopichandar** [neozhu/CleanArchitectureCodeGenerator#2]
With Visual Studio Version 16.11.3 - Showing COM object error in IntelisenceParser.cs file when clicking the "Add Feature" button.

![image](https://user-images.githubusercontent.com/13073344/133931671-626372ff-0bd2-4182-9c5f-359f85053d2c.png)

Any idea why?  I'm just getting started with this.

**Comment by neozhu** [comment]
sorry, I don't know, I only use Visual Studio 2022/2019. But this class(Intellisense*) is not necessary, you can annotate it.

**Comment by Gopichandar** [comment]
Version 16.11.3 is nothing but latest version of VS2019. Let me try annotate.

**Comment by neozhu** [comment]
There is a problem with visual studio 2019, It may be that the DLL libraries I refer to are the latest version 17-previews,
Microsoft.VisualStudio.SDK,Microsoft.VSSDK.BuildTools ,Downgrading these files to 16 should do the work.

**Comment by Gopichandar** [comment]
Thanks for the reply.  Instead of downgrading, I just upgraded my VS.  Hopefully, this should fix the issue.

**Comment by Gopichandar** [comment]
@neozhu I'm still having issues with Visual studio 2022 Version 17.0.0 Preview 4.1.  Any idea why?  am I missing any binaries here?

**Comment by Gopichandar** [comment]
Am I missing anything here? https://www.loom.com/share/69b69759f32f494284d81994499e0193

**Comment by neozhu** [comment]
![image](https://user-images.githubusercontent.com/1549611/134692867-218e5c9c-9f59-423e-be64-e90267a4d59b.png)
You check that the dependency reference is correct.
I was tested that not work in visual studio 2019. compile is ok.

**Comment by neozhu** [comment]
oh, I think that you running the project with the wrong way.  
You just compile and build, run install package:
![image](https://user-images.githubusercontent.com/1549611/134694930-10ca3754-88b1-4735-b4d8-021a3336707f.png)
then add new feature code in project
![image](https://user-images.githubusercontent.com/1549611/134695153-f7a5257a-59cd-46ba-9a6c-68e7ec4fc9f5.png)

**Comment by Gopichandar** [comment]
@neozhu  I tried installing it after building it in Release mode.  I see the same issue.  Also, I tried installing this from the market place still having the same issue.  I think I'm missing some binary.

**Comment by neozhu** [comment]
Hello @Gopichandar, I think  I fixed it. you can get the latest code. #Update IntellisenseParser.cs

**Comment by Gopichandar** [comment]
Thanks for the update @neozhu
