### ISSUE TITLE
Blazor or Razor?

### ISSUE THREAD

**Issue by DJJones66** [neozhu/CleanArchitectureCodeGenerator#23]
This works as expected under the CA:Blazor project but not the CA:Razor which is in the readme description.

**Comment by neozhu** [comment]
branch: main(brazor) for Blazor project(https://github.com/neozhu/CleanArchitectureWithBlazorServer)
branch: razor(not update) for RazorPage Project(https://github.com/neozhu/RazorPageCleanArchitecture)

**Comment by DJJones66** [comment]
That was such a duh moment there for me.  Thank you

Since not being updated, think will spend a little time and see if I can get a Razor.UI project going with some live inside the Blazor project.

Thanks again
