### ISSUE TITLE
Please Update Incompatible VS 2022 Clean Architecture CodeGenerator Extension

### ISSUE THREAD

**Issue by leslierichardson95** [neozhu/CleanArchitectureCodeGenerator#3]
Hi,
 
This is Leslie from the Visual Studio Extensibility team. I’m reaching out to you because we’ve received the following, high-priority feedback ticket for VS 2022: [Visual Studio Feedback](https://developercommunity.visualstudio.com/t/Could-not-load-file-or-assembly-EnvDTE/1463536) 
 
We determined that this issue is the result of extension(s) not being updated to Visual Studio 2022 properly due to marking VS 2022 as compatible in the VSIX manifest but not referencing the new SDK PIA (Microsoft.VisualStudio.Interop.dll) and dependencies.  We’ve identified that one of your extensions contributes to this issue:
 
•	**Clean Architecture CodeGenerator**
 
We strongly recommend that you update and re-publish your VSIX with the new VS 2022-compatible references, including EnvDTE.
 
Our investigation of the existing issue is that this happens when VS 2015 and VS 2022 are installed side by side, which is why it only occurred for a subset of customers.  Nevertheless, referencing older versions of VSSDK assemblies is not supported, especially for the APIs and types that we’ve listed as breaking or altered.  If you are doing so and find that your extensions work today, we make no guarantees that they will continue to work in the future.  Extension authors could also find themselves in a situation where their extensions negatively impacts users due to untested workflows.  From the product team’s perspective, we do not promise support to extension authors who do not follow our recommendation, and reference older versions of VSSDK.  We also reserve the right to mark these extensions as incompatible should we find that VS is negatively affected by them.  For the time being, instead of making VSIXValidator hard block any extensions that reference older assemblies, we will do a soft block and warn extension owners.  And since this particular scenario is niche enough that it only affects side by side installs, we will not be marking them as incompatible, yet.
 
We will be pushing out changes in the coming months to warn both extension authors as well as extension consumers if they are creating or using an extension that are built with older versions of the VSSDK.  We will share more details about this in the future.
 
Q: How can I validate whether my extension has dependencies on the old PIAs assembly?
A: You can try to validate the extension’s reference by following the steps below
1.	Open the Developer [command prompt](https://docs.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2022).
2.	Run the command [ildasm](https://docs.microsoft.com/en-us/dotnet/framework/tools/ildasm-exe-il-disassembler#examples) as below.
	* C:\>ildasm /text "{Extension Assembly}.dll"  /output:result.txt
3.	Check for references in the result.txt file.
 
 
 
 
For more info on how to migrate your extension to VS 2022 successfully, please view the following resources:
•	[Update Your Visual Studio Extension](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022)
•	[Breaking API List](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/breaking-api-list?view=vs-2022)
•	[Migrated PIA List](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/migrated-assemblies?view=vs-2022)
 
Please let us know if you have any questions.
 
Leslie Richardson
Program Manager – Visual Studio
leslie.richardson@microsoft.com | @lyrichardson01

**Comment by fasteddys** [comment]
Hello also, the nuget dependencies need to be updated

![image](https://user-images.githubusercontent.com/96149622/146601693-b29ff932-3b27-44b5-bb6d-2c173a902e98.png)

**Comment by neozhu** [comment]
try this link download
https://marketplace.visualstudio.com/items?itemName=SmartCodeMVC5Enginever3898.247365
