### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by BogdanJak** [neozhu/CleanArchitectureCodeGenerator#36]
Hello

I downloaded your CodeGenerator project from the link https://github.com/neozhu/CleanArchitectureCodeGenerator.
On startup I get the following error.

![image](https://github.com/neozhu/CleanArchitectureCodeGenerator/assets/54505464/268e0b46-9595-4bca-9ba6-66a930526954)

I didn't change anything in your code. I am using VS 17.7.0 preview 1.0.
Do you know why this is happening?

Bogdan

**Comment by neozhu** [comment]
Hi Bogdan,
The error you encountered seems to indicate that the specific code shown in the image is not present in the project.

It seems that the icon file is not being loaded in the code. Please check the properties of your project's resource files. Please refer to the image I have uploaded for you.

<img width="897" alt="image" src="https://github.com/neozhu/CleanArchitectureCodeGenerator/assets/1549611/796645de-1f92-4fd2-8451-3c71f9b6bce5">

**Comment by BogdanJak** [comment]
There seems to be an error loading "Menus.ctmenu"

![image](https://github.com/neozhu/CleanArchitectureCodeGenerator/assets/54505464/999d84f0-6f88-479f-b66f-fa0fb2df82f2)

Bogdan

**Comment by neozhu** [comment]
I might not be able to help you with this. I am unable to reproduce your issue on my end. Perhaps you can try deleting the "bin" directory in the project, building with debug, and then reinstalling to see if it resolves the problem.
