### ISSUE TITLE
Does not pick up models

### ISSUE THREAD

**Issue by hotfirewire** [neozhu/CleanArchitectureCodeGenerator#4]
I've tried running the extension and I'm having an issue with it recognizing the models I have in the project.  It only seems to find the TODO models that were already in the project template.  I've confirmed these other models are correct and work as expected.  Am I missing something?

**Comment by neozhu** [comment]
You can be debugging follow code:
var includes = new string[] { "IEntity", "AuditableEntity", "AuditableSoftDeleteEntity" };
			var entities = ProjectHelpers.GetEntities(domain.Project)
				.Where(x=>includes.Contains(x.BaseName) && !includes.Contains(x.Name))
				.Select(x=>x.Name)
				.Distinct().ToArray();
this mean that load entities from the domain project(Domain.csproj);

**Comment by neozhu** [comment]
now, I have fixed this bug

**Comment by hotfirewire** [comment]
The issue was I was using an updated version of the clean arch project and Jason changed the inheritance from AuditableEntity to BaseAuditableEntity on the classes.  After changing this it worked and showed up in the select list once again.
