### ISSUE TITLE
Dos not work with Visual studio 2022

### ISSUE THREAD

**Issue by DataTowerSystems** [neozhu/CleanArchitectureCodeGenerator#7]
Hi,
I have installed the extension in VS 2022, but when I run it on the project it gives me this error
![image](https://user-images.githubusercontent.com/105343175/197383669-eb0b32d5-d410-4659-bfbd-27d0583ac9aa.png)

Thank you very much.

**Comment by neozhu** [comment]
could you share your project? it's working in my project

**Comment by DataTowerSystems** [comment]
Thank you very much for your quick response.
I have forked this project [CleanArchitectureWithBlazorServer](https://github.com/neozhu/CleanArchitectureWithBlazorServer)
But I do not no why it is not working.
BTW: I am using this version Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.3.6
Thank you very mcuh.

**Comment by neozhu** [comment]
I tested it no problem based on vs 17.3.6 and 17.4 pre v4. I don't know why?

**Comment by DataTowerSystems** [comment]
Really strange thing any how I will remove it and re install it again.

**Comment by kirkey** [comment]
I made it work,
1.  uninstall existing codegenerator.
2.  test and compile this project.
3.  look for the vsix on debug or release folder.
4.  install it... Viola!
