### ISSUE TITLE
Code Generation Errors

### ISSUE THREAD

**Issue by buda56** [neozhu/CleanArchitectureCodeGenerator#80]
Hi,
   I would like to report the following issues whilst doing a code generation, I have included screenshots.

1.  Advanced Specifications (the red fields do not exist in that table)
<img width="1119" alt="devenv_k8AICjWxt7" src="https://github.com/user-attachments/assets/06dc9633-1156-4746-8aad-e863c27075b8">

2. Import Snippets Command (fields are not in the table, string to int conversion error on field)
<img width="1058" alt="devenv_THQVjgWf0a" src="https://github.com/user-attachments/assets/dacab5d7-6d6b-403d-a3e5-741030b7b1ac">

3. Update Snippets Command Validator (field does not exist in the table)
<img width="817" alt="devenv_LkCPMwk0lX" src="https://github.com/user-attachments/assets/52cef95e-78d6-48ef-aaed-231a3a2f06e6">

4. Create Snippet Command Validator (field does not exist in the table)
<img width="677" alt="devenv_QY7hS48JNU" src="https://github.com/user-attachments/assets/50e89cb4-5417-4380-b002-dc353802142f">

5. Add/Edit Command Validator (field does not exist in the table)
<img width="801" alt="devenv_J3J7LuQl6I" src="https://github.com/user-attachments/assets/f4ab4f1c-a717-47fb-bfec-4e2dddc24f14">

Regards
Peter

**Comment by buda56** [comment]
Further to the above, another where it is calling a function that does not exist within the whole project..

<img width="807" alt="devenv_Ql6LrrURLg" src="https://github.com/user-attachments/assets/04923b86-553a-4cbf-ad57-4529809ccae7">

Regards
Peter

**Comment by neozhu** [comment]
please get latest repo from https://github.com/neozhu/CleanArchitectureWithBlazorServer
